version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: salon_postgres
    environment:
      POSTGRES_DB: salon_payroll
      POSTGRES_USER: salon_user
      POSTGRES_PASSWORD: salon_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - salon_network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: salon_redis
    ports:
      - "6379:6379"
    networks:
      - salon_network

  # Main Application
  app:
    build: .
    container_name: salon_app
    environment:
      DATABASE_URL: postgresql://salon_user:salon_password@postgres:5432/salon_payroll
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: your-secret-key-here
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - salon_network
    volumes:
      - ./uploads:/app/uploads

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: salon_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - salon_network

volumes:
  postgres_data:

networks:
  salon_network:
    driver: bridge
